import { BinderDefinition } from '@/types';

// Helper: create entries from a simple list of titles
function entries(titles: string[]): { title: string }[] {
  return titles.map(title => ({ title }));
}

// Helper: create entry with display name different from Wikipedia title
function entry(title: string, displayName: string): { title: string; displayName: string } {
  return { title, displayName };
}

export const BINDERS: BinderDefinition[] = [
  // Planets of the Solar System (8)
  {
    id: 'planets',
    name: 'Planets',
    description: 'The 8 planets of our Solar System',
    icon: '\u{1FA90}',
    color: 'from-indigo-900 to-blue-950',
    entries: [
      entry('Mercury (planet)', 'Mercury'),
      { title: 'Venus' },
      { title: 'Earth' },
      { title: 'Mars' },
      { title: 'Jupiter' },
      { title: 'Saturn' },
      { title: 'Uranus' },
      { title: 'Neptune' },
    ],
  },

  // Wonders of the World (14)
  {
    id: 'wonders',
    name: 'Wonders of the World',
    description: '7 Ancient and 7 New Wonders',
    icon: '\u{1F3DB}\uFE0F',
    color: 'from-amber-900 to-yellow-950',
    entries: [
      entry('Great Pyramid of Giza', 'Great Pyramid of Giza'),
      entry('Hanging Gardens of Babylon', 'Hanging Gardens of Babylon'),
      entry('Statue of Zeus at Olympia', 'Statue of Zeus at Olympia'),
      entry('Temple of Artemis', 'Temple of Artemis'),
      entry('Mausoleum at Halicarnassus', 'Mausoleum at Halicarnassus'),
      entry('Colossus of Rhodes', 'Colossus of Rhodes'),
      entry('Lighthouse of Alexandria', 'Lighthouse of Alexandria'),
      entry('Great Wall of China', 'Great Wall of China'),
      entry('Petra', 'Petra'),
      entry('Colosseum', 'Colosseum'),
      entry('Chichen Itza', 'Chichen Itza'),
      entry('Machu Picchu', 'Machu Picchu'),
      entry('Taj Mahal', 'Taj Mahal'),
      entry('Christ the Redeemer (statue)', 'Christ the Redeemer'),
    ],
  },

  // U.S. Presidents (45)
  {
    id: 'us-presidents',
    name: 'U.S. Presidents',
    description: 'All 45 Presidents of the United States',
    icon: '\u{1F1FA}\u{1F1F8}',
    color: 'from-red-900 to-blue-950',
    entries: [
      { title: 'George Washington' },
      { title: 'John Adams' },
      { title: 'Thomas Jefferson' },
      { title: 'James Madison' },
      { title: 'James Monroe' },
      { title: 'John Quincy Adams' },
      { title: 'Andrew Jackson' },
      { title: 'Martin Van Buren' },
      entry('William Henry Harrison', 'William H. Harrison'),
      { title: 'John Tyler' },
      entry('James K. Polk', 'James K. Polk'),
      { title: 'Zachary Taylor' },
      { title: 'Millard Fillmore' },
      { title: 'Franklin Pierce' },
      { title: 'James Buchanan' },
      { title: 'Abraham Lincoln' },
      { title: 'Andrew Johnson' },
      entry('Ulysses S. Grant', 'Ulysses S. Grant'),
      entry('Rutherford B. Hayes', 'Rutherford B. Hayes'),
      entry('James A. Garfield', 'James A. Garfield'),
      { title: 'Chester A. Arthur' },
      { title: 'Grover Cleveland' },
      { title: 'Benjamin Harrison' },
      { title: 'William McKinley' },
      { title: 'Theodore Roosevelt' },
      entry('William Howard Taft', 'William H. Taft'),
      { title: 'Woodrow Wilson' },
      { title: 'Warren G. Harding' },
      { title: 'Calvin Coolidge' },
      { title: 'Herbert Hoover' },
      { title: 'Franklin D. Roosevelt' },
      { title: 'Harry S. Truman' },
      { title: 'Dwight D. Eisenhower' },
      { title: 'John F. Kennedy' },
      { title: 'Lyndon B. Johnson' },
      { title: 'Richard Nixon' },
      { title: 'Gerald Ford' },
      { title: 'Jimmy Carter' },
      { title: 'Ronald Reagan' },
      entry('George H. W. Bush', 'George H.W. Bush'),
      { title: 'Bill Clinton' },
      entry('George W. Bush', 'George W. Bush'),
      { title: 'Barack Obama' },
      { title: 'Donald Trump' },
      { title: 'Joe Biden' },
    ],
  },

  // Chemical Elements (118)
  {
    id: 'elements',
    name: 'Chemical Elements',
    description: 'All 118 elements of the periodic table',
    icon: '\u269B\uFE0F',
    color: 'from-emerald-900 to-teal-950',
    entries: entries([
      'Hydrogen', 'Helium', 'Lithium', 'Beryllium', 'Boron',
      'Carbon', 'Nitrogen', 'Oxygen', 'Fluorine', 'Neon',
      'Sodium', 'Magnesium', 'Aluminium', 'Silicon', 'Phosphorus',
      'Sulfur', 'Chlorine', 'Argon', 'Potassium', 'Calcium',
      'Scandium', 'Titanium', 'Vanadium', 'Chromium', 'Manganese',
      'Iron', 'Cobalt', 'Nickel', 'Copper', 'Zinc',
      'Gallium', 'Germanium', 'Arsenic', 'Selenium', 'Bromine',
      'Krypton', 'Rubidium', 'Strontium', 'Yttrium', 'Zirconium',
      'Niobium', 'Molybdenum', 'Technetium', 'Ruthenium', 'Rhodium',
      'Palladium', 'Silver', 'Cadmium', 'Indium', 'Tin',
      'Antimony', 'Tellurium', 'Iodine', 'Xenon', 'Caesium',
      'Barium', 'Lanthanum', 'Cerium', 'Praseodymium', 'Neodymium',
      'Promethium', 'Samarium', 'Europium', 'Gadolinium', 'Terbium',
      'Dysprosium', 'Holmium', 'Erbium', 'Thulium', 'Ytterbium',
      'Lutetium', 'Hafnium', 'Tantalum', 'Tungsten', 'Rhenium',
      'Osmium', 'Iridium', 'Platinum', 'Gold', 'Mercury (element)',
      'Thallium', 'Lead', 'Bismuth', 'Polonium', 'Astatine',
      'Radon', 'Francium', 'Radium', 'Actinium', 'Thorium',
      'Protactinium', 'Uranium', 'Neptunium', 'Plutonium', 'Americium',
      'Curium', 'Berkelium', 'Californium', 'Einsteinium', 'Fermium',
      'Mendelevium', 'Nobelium', 'Lawrencium', 'Rutherfordium', 'Dubnium',
      'Seaborgium', 'Bohrium', 'Hassium', 'Meitnerium', 'Darmstadtium',
      'Roentgenium', 'Copernicium', 'Nihonium', 'Flerovium', 'Moscovium',
      'Livermorium', 'Tennessine', 'Oganesson',
    ]),
  },

  // Countries of the World (195)
  {
    id: 'countries',
    name: 'Countries of the World',
    description: 'All 195 sovereign nations',
    icon: '\u{1F30D}',
    color: 'from-sky-900 to-cyan-950',
    entries: [
      { title: 'Afghanistan' },
      { title: 'Albania' },
      { title: 'Algeria' },
      { title: 'Andorra' },
      { title: 'Angola' },
      { title: 'Antigua and Barbuda' },
      { title: 'Argentina' },
      { title: 'Armenia' },
      { title: 'Australia' },
      { title: 'Austria' },
      { title: 'Azerbaijan' },
      { title: 'Bahamas' },
      { title: 'Bahrain' },
      { title: 'Bangladesh' },
      { title: 'Barbados' },
      { title: 'Belarus' },
      { title: 'Belgium' },
      { title: 'Belize' },
      { title: 'Benin' },
      { title: 'Bhutan' },
      { title: 'Bolivia' },
      { title: 'Bosnia and Herzegovina' },
      { title: 'Botswana' },
      { title: 'Brazil' },
      { title: 'Brunei' },
      { title: 'Bulgaria' },
      { title: 'Burkina Faso' },
      { title: 'Burundi' },
      entry('Cabo Verde', 'Cape Verde'),
      { title: 'Cambodia' },
      { title: 'Cameroon' },
      { title: 'Canada' },
      { title: 'Central African Republic' },
      { title: 'Chad' },
      { title: 'Chile' },
      { title: 'China' },
      { title: 'Colombia' },
      { title: 'Comoros' },
      entry('Democratic Republic of the Congo', 'DR Congo'),
      entry('Republic of the Congo', 'Congo'),
      { title: 'Costa Rica' },
      entry('Ivory Coast', "C\u00F4te d'Ivoire"),
      { title: 'Croatia' },
      { title: 'Cuba' },
      { title: 'Cyprus' },
      { title: 'Czech Republic' },
      { title: 'Denmark' },
      { title: 'Djibouti' },
      { title: 'Dominica' },
      { title: 'Dominican Republic' },
      { title: 'Ecuador' },
      { title: 'Egypt' },
      { title: 'El Salvador' },
      { title: 'Equatorial Guinea' },
      { title: 'Eritrea' },
      { title: 'Estonia' },
      { title: 'Eswatini' },
      { title: 'Ethiopia' },
      { title: 'Fiji' },
      { title: 'Finland' },
      { title: 'France' },
      { title: 'Gabon' },
      { title: 'Gambia' },
      entry('Georgia (country)', 'Georgia'),
      { title: 'Germany' },
      { title: 'Ghana' },
      { title: 'Greece' },
      { title: 'Grenada' },
      { title: 'Guatemala' },
      { title: 'Guinea' },
      { title: 'Guinea-Bissau' },
      { title: 'Guyana' },
      { title: 'Haiti' },
      { title: 'Honduras' },
      { title: 'Hungary' },
      { title: 'Iceland' },
      { title: 'India' },
      { title: 'Indonesia' },
      { title: 'Iran' },
      { title: 'Iraq' },
      entry('Republic of Ireland', 'Ireland'),
      { title: 'Israel' },
      { title: 'Italy' },
      { title: 'Jamaica' },
      { title: 'Japan' },
      { title: 'Jordan' },
      { title: 'Kazakhstan' },
      { title: 'Kenya' },
      { title: 'Kiribati' },
      { title: 'North Korea' },
      { title: 'South Korea' },
      { title: 'Kuwait' },
      { title: 'Kyrgyzstan' },
      { title: 'Laos' },
      { title: 'Latvia' },
      { title: 'Lebanon' },
      { title: 'Lesotho' },
      { title: 'Liberia' },
      { title: 'Libya' },
      { title: 'Liechtenstein' },
      { title: 'Lithuania' },
      { title: 'Luxembourg' },
      { title: 'Madagascar' },
      { title: 'Malawi' },
      { title: 'Malaysia' },
      { title: 'Maldives' },
      { title: 'Mali' },
      { title: 'Malta' },
      { title: 'Marshall Islands' },
      { title: 'Mauritania' },
      { title: 'Mauritius' },
      { title: 'Mexico' },
      entry('Federated States of Micronesia', 'Micronesia'),
      { title: 'Moldova' },
      { title: 'Monaco' },
      { title: 'Mongolia' },
      { title: 'Montenegro' },
      { title: 'Morocco' },
      { title: 'Mozambique' },
      { title: 'Myanmar' },
      { title: 'Namibia' },
      { title: 'Nauru' },
      { title: 'Nepal' },
      { title: 'Netherlands' },
      { title: 'New Zealand' },
      { title: 'Nicaragua' },
      { title: 'Niger' },
      { title: 'Nigeria' },
      { title: 'North Macedonia' },
      { title: 'Norway' },
      { title: 'Oman' },
      { title: 'Pakistan' },
      { title: 'Palau' },
      { title: 'Palestine' },
      { title: 'Panama' },
      { title: 'Papua New Guinea' },
      { title: 'Paraguay' },
      { title: 'Peru' },
      { title: 'Philippines' },
      { title: 'Poland' },
      { title: 'Portugal' },
      { title: 'Qatar' },
      { title: 'Romania' },
      { title: 'Russia' },
      { title: 'Rwanda' },
      { title: 'Saint Kitts and Nevis' },
      { title: 'Saint Lucia' },
      { title: 'Saint Vincent and the Grenadines' },
      { title: 'Samoa' },
      { title: 'San Marino' },
      entry('S\u00E3o Tom\u00E9 and Pr\u00EDncipe', 'S\u00E3o Tom\u00E9 and Pr\u00EDncipe'),
      { title: 'Saudi Arabia' },
      { title: 'Senegal' },
      { title: 'Serbia' },
      { title: 'Seychelles' },
      { title: 'Sierra Leone' },
      { title: 'Singapore' },
      { title: 'Slovakia' },
      { title: 'Slovenia' },
      { title: 'Solomon Islands' },
      { title: 'Somalia' },
      { title: 'South Africa' },
      { title: 'South Sudan' },
      { title: 'Spain' },
      { title: 'Sri Lanka' },
      { title: 'Sudan' },
      { title: 'Suriname' },
      { title: 'Sweden' },
      { title: 'Switzerland' },
      { title: 'Syria' },
      { title: 'Tajikistan' },
      { title: 'Tanzania' },
      { title: 'Thailand' },
      { title: 'East Timor' },
      { title: 'Togo' },
      { title: 'Tonga' },
      { title: 'Trinidad and Tobago' },
      { title: 'Tunisia' },
      { title: 'Turkey' },
      { title: 'Turkmenistan' },
      { title: 'Tuvalu' },
      { title: 'Uganda' },
      { title: 'Ukraine' },
      { title: 'United Arab Emirates' },
      { title: 'United Kingdom' },
      { title: 'United States' },
      { title: 'Uruguay' },
      { title: 'Uzbekistan' },
      { title: 'Vanuatu' },
      { title: 'Vatican City' },
      { title: 'Venezuela' },
      { title: 'Vietnam' },
      { title: 'Yemen' },
      { title: 'Zambia' },
      { title: 'Zimbabwe' },
    ],
  },
];

// Get display name for a binder entry
export function getEntryDisplayName(entry: { title: string; displayName?: string }): string {
  return entry.displayName || entry.title;
}

// Build a lookup map once (card title lowercase -> binder names)
let _binderLookup: Map<string, { name: string; icon: string }[]> | null = null;

export function getBindersForCard(cardTitle: string): { name: string; icon: string }[] {
  if (!_binderLookup) {
    _binderLookup = new Map();
    for (const binder of BINDERS) {
      for (const entry of binder.entries) {
        const key = entry.title.toLowerCase();
        const existing = _binderLookup.get(key) || [];
        existing.push({ name: binder.name, icon: binder.icon });
        _binderLookup.set(key, existing);
      }
    }
  }
  return _binderLookup.get(cardTitle.toLowerCase()) || [];
}
